version: "3.9"

services:
  web:
    build: .
    command: gunicorn NewsBoard.wsgi --bind 0.0.0.0:8000 --timeout 90
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  broker:
    image: "redis:alpine"
    ports:
      - 6379:6379
